travis:
  secure:
    BINSTAR_TOKEN: f0INJUKL0ZQzCdv2HAyOEQbWdSCuMzPe8+4y1RPOJQj1GCC/oAL3AfJ8y+cAAaWHYlvL9hLsi1pZSaTNzHgBozBOEoqc515jvNgDs4i3CvYYSzCE4HyLs8L12JcXtBnkTYqkbYwwRFJkHo+QcROAcPK5LXDfpkavqtAyBCZGfnLRlwdmlosl5+BgKHJlZr8LmARRKKW+NJ6/smoplyVJMJEMYjja0AK+fWzkpCC4o0A5w/3TTSUlkyZKfgBIclh1LEhi19Wd0ptt11HPJfZS0Y4IyOloIasZRsRcXk14WLz7c8Jw0b9+aoSRtRoGnL3HBBlaRaQ694WWtzNHAGM+uA5WYyUch6yVwlwqnLEfUUSxMN0RJXaEwE5SALrTH+7dAv/tPYZHVaP0tC/MPRBx1oD+jXlvpKQvHqHSm1cBH47kthVRcFIhsAqtp5fzQs88i4rheWlfmsLILL/GY2tLVcnhXDHwyZD6gu2wRP2WgPftxZ9dMfWhwXgRfPeOXCETYNKXvp5CDuEfsuWvjJMPH/+1TfZKa1mPrexOpkOBtb3VLmLeztRR5t7WFioTbZfSGYhA2XrtJzQr0K2obtCIxXWYXYrPPLAmVDNZauc26/FA7pYwCn7HDX/gXW17/EuCj2YOZDGF9jm5YVYgbRBNSeUZ4qj/kBdhio9xCFTWFGo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
